#!/bin/bash

sudo qemu-system-x86_64 \
  -enable-kvm \
  -m 8G \
  -machine q35,accel=kvm \
  -smp 4,cores=2 \
  -cpu Penryn,vendor=GenuineIntel,kvm=on,+ssse3,+sse4.2,+aes,+xsave,+avx,+xsaveopt,+xsavec,+xgetbv1,+avx2,+bmi2,+smep,+bmi1,+fma,+movbe,+invtsc \
  -device isa-applesmc,osk="insert-real-64-char-OSK-here" \
  -smbios type=2 \
  -drive if=pflash,format=raw,readonly=on,file=OVMF_CODE.fd \
  -drive if=pflash,format=raw,file=OVMF_VARS.fd \
  -device ich9-intel-hda -device hda-output \
  -device ich9-ahci,id=sata \
  -drive id=MacHDD,if=none,format=raw,file=/dev/sda \
  -device ide-hd,bus=sata.4,drive=MacHDD \
  -netdev user,id=net0 \
  -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27